package relay

import (
	"encoding/json"
	"html"
	"net/http"
	"path"
	"strings"

	"github.com/gorilla/websocket"
	"github.com/poouo/BeaconDesk/internal/protocol"
)

func (s *Server) mountWebControl(mux *http.ServeMux, upgrader websocket.Upgrader) {
	if !s.cfg.WebControlEnabled {
		return
	}
	base := s.webControlPath()
	mux.HandleFunc(base, s.handleWebControlHome)
	mux.HandleFunc(base+"/", func(w http.ResponseWriter, r *http.Request) {
		rel := strings.TrimPrefix(r.URL.Path, base)
		switch {
		case strings.HasPrefix(rel, "/s/"):
			s.handleWebSharePage(w, r)
		case rel == "/ws":
			s.handleWebControlWS(w, r, upgrader)
		default:
			http.NotFound(w, r)
		}
	})
}

func (s *Server) handleWebControlHome(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != s.webControlPath() {
		http.NotFound(w, r)
		return
	}
	writeHTML(w, http.StatusOK, webHomeHTML())
}

func (s *Server) handleWebSharePage(w http.ResponseWriter, r *http.Request) {
	token := path.Base(r.URL.Path)
	share, err := s.getActiveWebShare(token)
	if err != nil {
		writeHTML(w, http.StatusNotFound, webErrorHTML("链接不可用", "This link is unavailable", err.Error()))
		return
	}
	writeHTML(w, http.StatusOK, webControlHTML(s.webControlPath(), share, s.webShareURL(token, r)))
}

func (s *Server) handleWebControlWS(w http.ResponseWriter, r *http.Request, upgrader websocket.Upgrader) {
	token := r.URL.Query().Get("token")
	share, err := s.getActiveWebShare(token)
	if err != nil {
		http.Error(w, err.Error(), http.StatusForbidden)
		return
	}
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		s.logger.Warn("web control websocket upgrade failed", "error", err)
		return
	}
	conn.SetReadLimit(protocol.MaxLineBytes)

	peer := newWebPeer(s, conn, share)
	peer.run(r.Context())
}

func writeHTML(w http.ResponseWriter, status int, body string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.WriteHeader(status)
	_, _ = w.Write([]byte(body))
}

func webHomeHTML() string {
	return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BeaconDesk Web Control</title><style>` + webCSS() + `</style></head><body><main class="center"><section class="panel"><h1>BeaconDesk 网页控制</h1><p>请使用被控端生成的临时网页控制链接访问。链接不会直接授权控制，被控端仍需在本机明确同意。</p><p class="muted">Use a temporary control link generated by the controlled device. The controlled user must still approve every session locally.</p></section></main></body></html>`
}

func webErrorHTML(zhTitle, enTitle, detail string) string {
	return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BeaconDesk</title><style>` + webCSS() + `</style></head><body><main class="center"><section class="panel"><h1>` + html.EscapeString(zhTitle) + `</h1><p>` + html.EscapeString(enTitle) + `</p><p class="muted">` + html.EscapeString(detail) + `</p></section></main></body></html>`
}

func webControlHTML(base string, share *WebShare, link string) string {
	payload, _ := json.Marshal(struct {
		Base       string `json:"base"`
		Token      string `json:"token"`
		Mode       string `json:"mode"`
		Target     string `json:"target"`
		TargetName string `json:"target_name"`
		ExpiresAt  int64  `json:"expires_at"`
	}{
		Base:       base,
		Token:      share.Token,
		Mode:       share.Mode,
		Target:     share.ControlledID,
		TargetName: share.ControlledName,
		ExpiresAt:  share.ExpiresAt.UnixMilli(),
	})
	return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BeaconDesk Web Control</title><style>` + webCSS() + `</style></head><body><main class="app"><header><div><h1>BeaconDesk 网页控制</h1><p>目标：` + html.EscapeString(share.ControlledName) + ` (` + html.EscapeString(share.ControlledID) + `)</p></div><div class="badge" id="status">等待连接</div></header><section class="toolbar"><button id="connect">请求连接</button><button id="close" disabled>断开</button><span>链接有效期至 ` + html.EscapeString(share.ExpiresAt.Local().Format("2006-01-02 15:04:05")) + `</span></section><section class="notice">此链接只用于发起网页协助请求。被控端必须在本机点击允许后，浏览器才能看到画面并发送输入。</section><section class="screen"><img id="frame" alt="remote frame"><div id="placeholder">等待被控端授权和画面帧...</div></section><footer><span>` + html.EscapeString(link) + `</span></footer></main><script>window.__BEACONDESK__=` + string(payload) + `;</script><script>` + webJS() + `</script></body></html>`
}

func webCSS() string {
	return `*{box-sizing:border-box}body{margin:0;background:#eef3f8;color:#142033;font:14px/1.45 "Segoe UI",Arial,"Microsoft YaHei",sans-serif}.center{min-height:100vh;display:grid;place-items:center;padding:24px}.panel{width:min(720px,100%);background:#fff;border:1px solid #d8e1ee;border-radius:8px;padding:28px;box-shadow:0 18px 50px rgba(15,23,42,.10)}h1{margin:0 0 10px;font-size:24px}.muted{color:#5b6678}.app{min-height:100vh;display:grid;grid-template-rows:auto auto auto 1fr auto;gap:12px;padding:16px}header,.toolbar,.notice,footer{background:#fff;border:1px solid #d8e1ee;border-radius:8px;padding:12px 14px}header{display:flex;align-items:center;justify-content:space-between;gap:12px}header h1{font-size:20px;margin:0}header p{margin:4px 0 0;color:#5b6678}.badge{border-radius:999px;background:#e6efff;color:#195ab4;padding:7px 10px;font-weight:700}.toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.toolbar span,footer{color:#5b6678}button{border:0;border-radius:8px;background:#2563eb;color:#fff;font-weight:700;padding:9px 14px;cursor:pointer}button:disabled{background:#d5dce8;color:#7d8796;cursor:not-allowed}.notice{background:#fff7ed;color:#9a3412}.screen{position:relative;min-height:360px;background:#0b1220;border-radius:8px;overflow:hidden;display:grid;place-items:center}.screen img{display:none;max-width:100%;max-height:calc(100vh - 230px);object-fit:contain}.screen.has-frame img{display:block}.screen.has-frame #placeholder{display:none}#placeholder{color:#d8e1ee}`
}

func webJS() string {
	return `(()=>{const cfg=window.__BEACONDESK__;const status=document.getElementById("status");const connect=document.getElementById("connect");const closeBtn=document.getElementById("close");const img=document.getElementById("frame");const screen=document.querySelector(".screen");let ws=null,session="",inputAllowed=false,frameSize={w:0,h:0};function setStatus(v){status.textContent=v}function envelope(type,payload){return{version:1,type,session_id:session,payload}}function send(type,payload){if(ws&&ws.readyState===1)ws.send(JSON.stringify(envelope(type,payload)))}function wsURL(){const proto=location.protocol==="https:"?"wss":"ws";return proto+"://"+location.host+cfg.base+"/ws?token="+encodeURIComponent(cfg.token)}connect.onclick=()=>{if(ws)return;ws=new WebSocket(wsURL());setStatus("连接中");connect.disabled=true;closeBtn.disabled=false;ws.onopen=()=>setStatus("等待被控端同意");ws.onclose=()=>{setStatus("已断开");ws=null;session="";inputAllowed=false;connect.disabled=false;closeBtn.disabled=true};ws.onerror=()=>setStatus("连接出错");ws.onmessage=(ev)=>{let msg;try{msg=JSON.parse(ev.data)}catch{return}const p=msg.payload||{};if(msg.type==="web.share.status"){setStatus(p.message||p.status||"等待中")}else if(msg.type==="session.ready"){session=p.session_id||msg.session_id;inputAllowed=!!p.input_allowed;setStatus(inputAllowed?"已连接，可控制":"已连接，仅观看")}else if(msg.type==="session.confirm"&&!p.accepted){setStatus(p.reason||"被控端已拒绝")}else if(msg.type==="session.close"){setStatus("会话已关闭");if(ws)ws.close()}else if(msg.type==="stream.frame"){if(p.kind==="jpeg"&&p.data){img.src="data:image/jpeg;base64,"+p.data;frameSize={w:p.width||0,h:p.height||0};screen.classList.add("has-frame")}}else if(msg.type==="error"){setStatus(p.message||"错误")}}};closeBtn.onclick=()=>{if(ws){send("session.close",{});ws.close()}};function pos(e){const r=img.getBoundingClientRect();const x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));const y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));return{x:Math.round(x*(frameSize.w||r.width)),y:Math.round(y*(frameSize.h||r.height)),source_width:frameSize.w||Math.round(r.width),source_height:frameSize.h||Math.round(r.height)}}function mouse(action,e){if(!session||!inputAllowed||!screen.classList.contains("has-frame"))return;e.preventDefault();const p=pos(e);p.action=action;p.button=e.button===2?"right":e.button===1?"middle":"left";send("input.mouse",p)}img.addEventListener("mousedown",e=>mouse("down",e));img.addEventListener("mouseup",e=>mouse("up",e));img.addEventListener("mousemove",e=>{if(e.buttons)mouse("move",e)});img.addEventListener("wheel",e=>{if(!session||!inputAllowed)return;e.preventDefault();const p=pos(e);p.action="wheel";p.wheel_delta=Math.trunc(-e.deltaY);send("input.mouse",p)},{passive:false});window.addEventListener("keydown",e=>{if(!session||!inputAllowed)return;send("input.keyboard",{key:e.key,code:e.code,key_code:e.keyCode,action:"down",modifiers:mods(e)})});window.addEventListener("keyup",e=>{if(!session||!inputAllowed)return;send("input.keyboard",{key:e.key,code:e.code,key_code:e.keyCode,action:"up",modifiers:mods(e)})});function mods(e){const m=[];if(e.ctrlKey)m.push("ctrl");if(e.shiftKey)m.push("shift");if(e.altKey)m.push("alt");if(e.metaKey)m.push("meta");return m}})();`
}
